export default { 
    products:[
        {
            _id:'1',
            name:'Necklace1',
            category:'Necklace',
            image:'/images/necklace1.jpg'
        },
        {
            _id:'2',
            name:'Necklace2',
            category:'Necklace',
            image:'/images/necklace2.jpg'
        },
        {
            _id:'3',
            name:'Necklace3',
            category:'Necklace',
            image:'/images/necklace3.jpg'
        },
        {
            _id:'4',
            name:'Necklace4',
            category:'Necklace',
            image:'/images/necklace4.jpg'
        },
        {
            _id:'5',
            name:'Necklace5',
            category:'Necklace',
            image:'/images/necklace5.jpg'
        },
        {
            _id:'6',
            name:'Necklace6',
            category:'Necklace',
            image:'/images/necklace6.jpg'
        },
    ],
};